name: Sriraracha Snake

on:
  push:
    branches: [ "main" ] #everytime sth is pushed to this branch, the following sgould happen

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      run: |
        pytest
        pylint spicy_snake/*.py
        pylint tests/*.py